#include "dex/disasm.h"

#define LOOKUP_ITEM(op, mnemonic, fmt_) [op] = { .name = mnemonic, .fmt = FMT##fmt_ }

struct InstrLookup instrInfo[COUNT] = {
    LOOKUP_ITEM(NOP, "nop", _10x),
    LOOKUP_ITEM(MOVE, "move", _12x),
    LOOKUP_ITEM(MOVE_FROM16, "move/from16", _22x),
    LOOKUP_ITEM(MOVE_16, "move/16", _32x),
    LOOKUP_ITEM(MOVE_WIDE, "move-wide", _12x),
    LOOKUP_ITEM(MOVE_WIDE_FROM_16, "move-wide/from16", _22x),
    LOOKUP_ITEM(MOVE_WIDE_16, "move-wide/16", _32x),
    LOOKUP_ITEM(MOVE_OBJECT, "move-object", _12x),
    LOOKUP_ITEM(MOVE_OBJECT_FROM_16, "move-object/from16", _22x),
    LOOKUP_ITEM(MOVE_OBJECT_16, "move-object/16", _32x),
    LOOKUP_ITEM(MOVE_RESULT, "move-result", _11x),
    LOOKUP_ITEM(MOVE_RESULT_WIDE, "move-result-wide", _11x),
    LOOKUP_ITEM(MOVE_RESULT_OBJECT, "move-result-object", _11x),
    LOOKUP_ITEM(MOVE_EXCEPTION, "move-exception", _11x),
    LOOKUP_ITEM(RETURN_VOID, "return-void", _10x),
    LOOKUP_ITEM(RETURN, "return", _11x),
    LOOKUP_ITEM(RETURN_WIDE, "return-wide", _11x),
    LOOKUP_ITEM(RETURN_OBJECT, "return-object", _11x),
    LOOKUP_ITEM(CONST_4, "const/4", _11n),
    LOOKUP_ITEM(CONST_16, "const/16", _21s),
    LOOKUP_ITEM(CONST, "const", _31i),
    LOOKUP_ITEM(CONST_HIGH_16, "const/high16", _21h),
    LOOKUP_ITEM(CONST_WIDE_16, "const-wide/16", _21h),
    LOOKUP_ITEM(CONST_WIDE_32, "const-wide/32", _31i),
    LOOKUP_ITEM(CONST_WIDE, "const-wide", _51l),
    LOOKUP_ITEM(CONST_WIDE_HIGH_16, "const-wide/high16", _21h),
    LOOKUP_ITEM(CONST_STRING, "const-string", _21c),
    LOOKUP_ITEM(CONST_STRING_JUMBO, "const-string/jumbo", _31c),
    LOOKUP_ITEM(CONST_CLASS, "const-class", _21c),
    LOOKUP_ITEM(MONITOR_ENTER, "monitor-enter", _11x),
    LOOKUP_ITEM(MONITOR_EXIT, "monitor-exit", _11x),
    LOOKUP_ITEM(CHECK_CAST, "check-cast", _21c),
    LOOKUP_ITEM(INSTANCE_OF, "instance-of", _22c),
    LOOKUP_ITEM(ARRAY_LENGTH, "array-length", _12x),
    LOOKUP_ITEM(NEW_INSTANCE, "new-instance", _21c),
    LOOKUP_ITEM(NEW_ARRAY, "new-array", _22c),
    LOOKUP_ITEM(FILLED_NEW_ARRAY, "filled-new-array", _35c),
    LOOKUP_ITEM(FILLED_NEW_ARRAY_RANGE, "filled-new-array/range", _3rc),
    LOOKUP_ITEM(FILL_ARRAY_DATA, "fill-array-data", _31t),
    LOOKUP_ITEM(THROW, "throw", _11x),
    LOOKUP_ITEM(GOTO, "goto", _10t),
    LOOKUP_ITEM(GOTO_16, "goto/16", _20t),
    LOOKUP_ITEM(GOTO_32, "goto/32", _30t),
    LOOKUP_ITEM(PACKED_SWITCH, "packed-switch", _31t),
    LOOKUP_ITEM(SPARSE_SWITCH, "sparse-switch", _31t),

    LOOKUP_ITEM(CMPL_FLOAT, "cmpl-float", _23x),
    LOOKUP_ITEM(CMPG_FLOAT, "cmpg-float", _23x),
    LOOKUP_ITEM(CMPL_DOUBLE, "cmpl-double", _23x),
    LOOKUP_ITEM(CMPG_DOUBLE, "cmpg-double", _23x),
    LOOKUP_ITEM(CMP_LONG, "cmp-long", _23x),

    LOOKUP_ITEM(IF_EQ, "if-eq", _22t),
    LOOKUP_ITEM(IF_NE, "if-ne", _22t),
    LOOKUP_ITEM(IF_LT, "if-lt", _22t),
    LOOKUP_ITEM(IF_GE, "if-ge", _22t),
    LOOKUP_ITEM(IF_GT, "if-gt", _22t),
    LOOKUP_ITEM(IF_LE, "if-le", _22t),

    LOOKUP_ITEM(IF_EQZ, "if-eqz", _21t),
    LOOKUP_ITEM(IF_NEZ, "if-nez", _21t),
    LOOKUP_ITEM(IF_LTZ, "if-ltz", _21t),
    LOOKUP_ITEM(IF_GEZ, "if-gez", _21t),
    LOOKUP_ITEM(IF_GTZ, "if-gtz", _21t),
    LOOKUP_ITEM(IF_LEZ, "if-lez", _21t),

    LOOKUP_ITEM(AGET, "aget", _23x),
    LOOKUP_ITEM(AGET_WIDE, "aget-wide", _23x),
    LOOKUP_ITEM(AGET_OBJECT, "aget-object", _23x),
    LOOKUP_ITEM(AGET_BOOLEAN, "aget-boolean", _23x),
    LOOKUP_ITEM(AGET_BYTE, "aget-byte", _23x),
    LOOKUP_ITEM(AGET_CHAR, "aget-char", _23x),
    LOOKUP_ITEM(AGET_SHORT, "aget-short", _23x),
    LOOKUP_ITEM(APUT, "aput", _23x),
    LOOKUP_ITEM(APUT_WIDE, "aput-wide", _23x),
    LOOKUP_ITEM(APUT_OBJECT, "aput-object", _23x),
    LOOKUP_ITEM(APUT_BOOLEAN, "aput-boolean", _23x),
    LOOKUP_ITEM(APUT_BYTE, "aput-byte", _23x),
    LOOKUP_ITEM(APUT_CHAR, "aput-char", _23x),
    LOOKUP_ITEM(APUT_SHORT, "aput-short", _23x),

    LOOKUP_ITEM(IGET, "iget", _22c),
    LOOKUP_ITEM(IGET_WIDE, "iget-wide", _22c),
    LOOKUP_ITEM(IGET_OBJECT, "iget-object", _22c),
    LOOKUP_ITEM(IGET_BOOLEAN, "iget-boolean", _22c),
    LOOKUP_ITEM(IGET_BYTE, "iget-byte", _22c),
    LOOKUP_ITEM(IGET_CHAR, "iget-char", _22c),
    LOOKUP_ITEM(IGET_SHORT, "iget-short", _22c),
    LOOKUP_ITEM(IPUT, "iput", _22c),
    LOOKUP_ITEM(IPUT_WIDE, "iput-wide", _22c),
    LOOKUP_ITEM(IPUT_OBJECT, "iput-object", _22c),
    LOOKUP_ITEM(IPUT_BOOLEAN, "iput-boolean", _22c),
    LOOKUP_ITEM(IPUT_BYTE, "iput-byte", _22c),
    LOOKUP_ITEM(IPUT_CHAR, "iput-char", _22c),
    LOOKUP_ITEM(IPUT_SHORT, "iput-short", _22c),

    LOOKUP_ITEM(SGET, "sget", _21c),
    LOOKUP_ITEM(SGET_WIDE, "sget-wide", _21c),
    LOOKUP_ITEM(SGET_OBJECT, "sget-object", _21c),
    LOOKUP_ITEM(SGET_BOOLEAN, "sget-boolean", _22c),
    LOOKUP_ITEM(SGET_BYTE, "sget-byte", _21c),
    LOOKUP_ITEM(SGET_CHAR, "sget-char", _21c),
    LOOKUP_ITEM(SGET_SHORT, "sget-short", _21c),
    LOOKUP_ITEM(SPUT, "sput", _21c),
    LOOKUP_ITEM(SPUT_WIDE, "sput-wide", _21c),
    LOOKUP_ITEM(SPUT_OBJECT, "sput-object", _21c),
    LOOKUP_ITEM(SPUT_BOOLEAN, "sput-boolean", _21c),
    LOOKUP_ITEM(SPUT_BYTE, "sput-byte", _21c),
    LOOKUP_ITEM(SPUT_CHAR, "sput-char", _21c),
    LOOKUP_ITEM(SPUT_SHORT, "sput-short", _21c),

    LOOKUP_ITEM(INVOKE_VIRTUAL, "invoke-virtual", _35c),
    LOOKUP_ITEM(INVOKE_SUPER, "invoke-super", _35c),
    LOOKUP_ITEM(INVOKE_DIRECT, "invoke-direct", _35c),
    LOOKUP_ITEM(INVOKE_STATIC, "invoke-static", _35c),
    LOOKUP_ITEM(INVOKE_INTERFACE, "invoke-interface", _35c),

    LOOKUP_ITEM(INVOKE_VIRTUAL_RANGE, "invoke-virtual/range", _3rc),
    LOOKUP_ITEM(INVOKE_SUPER_RANGE, "invoke-super/range", _3rc),
    LOOKUP_ITEM(INVOKE_DIRECT_RANGE, "invoke-direct/range", _3rc),
    LOOKUP_ITEM(INVOKE_STATIC_RANGE, "invoke-static/range", _3rc),
    LOOKUP_ITEM(INVOKE_INTERFACE_RANGE, "invoke-interface/range", _3rc),

    LOOKUP_ITEM(NEG_INT, "neg-int", _12x),
    LOOKUP_ITEM(NOT_INT, "not-int", _12x),
    LOOKUP_ITEM(NEG_LONG, "neg-long", _12x),
    LOOKUP_ITEM(NOT_LONG, "not-long", _12x),
    LOOKUP_ITEM(NEG_FLOAT, "neg-float", _12x),
    LOOKUP_ITEM(NEG_DOUBLE, "neg-double", _12x),
    LOOKUP_ITEM(INT_TO_LONG, "int-to-long", _12x),
    LOOKUP_ITEM(INT_TO_FLOAT, "int-to-float", _12x),
    LOOKUP_ITEM(INT_TO_DOUBLE, "int-to-double", _12x),
    LOOKUP_ITEM(LONG_TO_INT, "long-to-int", _12x),
    LOOKUP_ITEM(LONG_TO_FLOAT, "long-to-float", _12x),
    LOOKUP_ITEM(LONG_TO_DOUBLE, "long-to-double", _12x),
    LOOKUP_ITEM(FLOAT_TO_INT, "float-to-int", _12x),
    LOOKUP_ITEM(FLOAT_TO_LONG, "float-to-long", _12x),
    LOOKUP_ITEM(FLOAT_TO_DOUBLE, "float-to-double", _12x),
    LOOKUP_ITEM(DOUBLE_TO_INT, "double-to-int", _12x),
    LOOKUP_ITEM(DOUBLE_TO_LONG, "double-to-long", _12x),
    LOOKUP_ITEM(DOUBLE_TO_FLOAT, "double-to-float", _12x),
    LOOKUP_ITEM(INT_TO_BYTE, "int-to-byte", _12x),
    LOOKUP_ITEM(INT_TO_CHAR, "int-to-char", _12x),
    LOOKUP_ITEM(INT_TO_SHORT, "int-to-short", _12x),

    LOOKUP_ITEM(ADD_INT, "add-int", _23x),
    LOOKUP_ITEM(SUB_INT, "sub-int", _23x),
    LOOKUP_ITEM(MUL_INT, "mul-int", _23x),
    LOOKUP_ITEM(DIV_INT, "div-int", _23x),
    LOOKUP_ITEM(REM_INT, "rem-int", _23x),
    LOOKUP_ITEM(AND_INT, "and-int", _23x),
    LOOKUP_ITEM(OR_INT, "or-int", _23x),
    LOOKUP_ITEM(XOR_INT, "xor-int", _23x),
    LOOKUP_ITEM(SHL_INT, "shl-int", _23x),
    LOOKUP_ITEM(SHR_INT, "shr-int", _23x),
    LOOKUP_ITEM(USHR_INT, "ushr-int", _23x),

    LOOKUP_ITEM(ADD_LONG, "add-long", _23x),
    LOOKUP_ITEM(SUB_LONG, "sub-long", _23x),
    LOOKUP_ITEM(MUL_LONG, "mul-long", _23x),
    LOOKUP_ITEM(DIV_LONG, "div-long", _23x),
    LOOKUP_ITEM(REM_LONG, "rem-long", _23x),
    LOOKUP_ITEM(AND_LONG, "and-long", _23x),
    LOOKUP_ITEM(OR_LONG, "or-long", _23x),
    LOOKUP_ITEM(XOR_LONG, "xor-long", _23x),
    LOOKUP_ITEM(SHL_LONG, "shl-long", _23x),
    LOOKUP_ITEM(SHR_LONG, "shr-long", _23x),
    LOOKUP_ITEM(USHR_LONG, "ushr-long", _23x),

    LOOKUP_ITEM(ADD_FLOAT, "add-float", _23x),
    LOOKUP_ITEM(SUB_FLOAT, "sub-float", _23x),
    LOOKUP_ITEM(MUL_FLOAT, "mul-float", _23x),
    LOOKUP_ITEM(DIV_FLOAT, "div-float", _23x),
    LOOKUP_ITEM(REM_FLOAT, "rem-float", _23x),

    LOOKUP_ITEM(ADD_DOUBLE, "add-double", _23x),
    LOOKUP_ITEM(SUB_DOUBLE, "sub-double", _23x),
    LOOKUP_ITEM(MUL_DOUBLE, "mul-double", _23x),
    LOOKUP_ITEM(DIV_DOUBLE, "div-double", _23x),
    LOOKUP_ITEM(REM_DOUBLE, "rem-double", _23x),

    LOOKUP_ITEM(ADD_INT_2ADDR, "add-int/2addr", _12x),
    LOOKUP_ITEM(SUB_INT_2ADDR, "sub-int/2addr", _12x),
    LOOKUP_ITEM(MUL_INT_2ADDR, "mul-int/2addr", _12x),
    LOOKUP_ITEM(DIV_INT_2ADDR, "div-int/2addr", _12x),
    LOOKUP_ITEM(REM_INT_2ADDR, "rem-int/2addr", _12x),
    LOOKUP_ITEM(AND_INT_2ADDR, "and-int/2addr", _12x),
    LOOKUP_ITEM(OR_INT_2ADDR, "or-int/2addr", _12x),
    LOOKUP_ITEM(XOR_INT_2ADDR, "xor-int/2addr", _12x),
    LOOKUP_ITEM(SHL_INT_2ADDR, "shl-int/2addr", _12x),
    LOOKUP_ITEM(SHR_INT_2ADDR, "shr-int/2addr", _12x),
    LOOKUP_ITEM(USHR_INT_2ADDR, "ushr-int/2addr", _12x),

    LOOKUP_ITEM(ADD_LONG_2ADDR, "add-long/2addr", _12x),
    LOOKUP_ITEM(SUB_LONG_2ADDR, "sub-long/2addr", _12x),
    LOOKUP_ITEM(MUL_LONG_2ADDR, "mul-long/2addr", _12x),
    LOOKUP_ITEM(DIV_LONG_2ADDR, "div-long/2addr", _12x),
    LOOKUP_ITEM(REM_LONG_2ADDR, "rem-long/2addr", _12x),
    LOOKUP_ITEM(AND_LONG_2ADDR, "and-long/2addr", _12x),
    LOOKUP_ITEM(OR_LONG_2ADDR, "or-long/2addr", _12x),
    LOOKUP_ITEM(XOR_LONG_2ADDR, "xor-long/2addr", _12x),
    LOOKUP_ITEM(SHL_LONG_2ADDR, "shl-long/2addr", _12x),
    LOOKUP_ITEM(SHR_LONG_2ADDR, "shr-long/2addr", _12x),
    LOOKUP_ITEM(USHR_LONG_2ADDR, "ushr-long/2addr", _12x),

    LOOKUP_ITEM(ADD_FLOAT_2ADDR, "add-float/2addr", _12x),
    LOOKUP_ITEM(SUB_FLOAT_2ADDR, "sub-float/2addr", _12x),
    LOOKUP_ITEM(MUL_FLOAT_2ADDR, "mul-float/2addr", _12x),
    LOOKUP_ITEM(DIV_FLOAT_2ADDR, "div-float/2addr", _12x),
    LOOKUP_ITEM(REM_FLOAT_2ADDR, "rem-float/2addr", _12x),

    LOOKUP_ITEM(ADD_DOUBLE_2ADDR, "add-double/2addr", _12x),
    LOOKUP_ITEM(SUB_DOUBLE_2ADDR, "sub-double/2addr", _12x),
    LOOKUP_ITEM(MUL_DOUBLE_2ADDR, "mul-double/2addr", _12x),
    LOOKUP_ITEM(DIV_DOUBLE_2ADDR, "div-double/2addr", _12x),
    LOOKUP_ITEM(REM_DOUBLE_2ADDR, "rem-double/2addr", _12x),

    LOOKUP_ITEM(ADD_INT_LIT16, "add-int/lit16", _22s),
    LOOKUP_ITEM(RSUB_INT, "rsub-int", _22s),
    LOOKUP_ITEM(MUL_INT_LIT16, "mul-int/lit16", _22s),
    LOOKUP_ITEM(DIV_INT_LIT16, "div-int/lit16", _22s),
    LOOKUP_ITEM(REM_INT_LIT16, "rem-int/lit16", _22s),
    LOOKUP_ITEM(AND_INT_LIT16, "and-int/lit16", _22s),
    LOOKUP_ITEM(OR_INT_LIT16, "or-int/lit16", _22s),
    LOOKUP_ITEM(XOR_INT_LIT16, "xor-int/lit16", _22s),

    LOOKUP_ITEM(ADD_INT_LIT8, "add-int/lit8", _22b),
    LOOKUP_ITEM(RSUB_INT_LIT8, "rsub-int/lit8", _22b),
    LOOKUP_ITEM(MUL_INT_LIT8, "mul-int/lit8", _22b),
    LOOKUP_ITEM(DIV_INT_LIT8, "div-int/lit8", _22b),
    LOOKUP_ITEM(REM_INT_LIT8, "rem-int/lit8", _22b),
    LOOKUP_ITEM(AND_INT_LIT8, "and-int/lit8", _22b),
    LOOKUP_ITEM(OR_INT_LIT8, "or-int/lit8", _22b),
    LOOKUP_ITEM(XOR_INT_LIT8, "xor-int/lit8", _22b),
    LOOKUP_ITEM(SHL_INT_LIT8, "shl-int/lit8", _22b),
    LOOKUP_ITEM(SHR_INT_LIT8, "shr-int/lit8", _22b),
    LOOKUP_ITEM(USHR_INT_LIT8, "ushr-int/lit8", _22b),

    LOOKUP_ITEM(INVOKE_POLYMORPHIC, "invoke-polymorphic", _45cc),
    LOOKUP_ITEM(INVOKE_POLYMORPHIC_RANGE, "invoke-polymorphic/range", _4rcc),
    LOOKUP_ITEM(INVOKE_CUSTOM, "invoke-custom", _35c),
    LOOKUP_ITEM(INVOKE_CUSTOM_RANGE, "invoke-custom/range", _3rc),
    LOOKUP_ITEM(CONST_METHOD_HANDLE, "const-method-handle", _21c),
    LOOKUP_ITEM(CONST_METHOD_TYPE, "const-method-type", _21c),

    LOOKUP_ITEM(PACKED_SWITCH_PAYLOAD, "packed-switch-payload", _0),
    LOOKUP_ITEM(SPARSE_SWITCH_PAYLOAD, "sparse-switch-payload", _0),
    LOOKUP_ITEM(FILL_ARRAY_DATA_PAYLOAD, "fill-array-data-payload", _0)
};
